apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::120569644156:role/managed-group-eks-node-group-20241205165334665200000001
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::120569644156:user/charlie
      username: charlie
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::120569644156:role/managed-group-eks-node-group-20241205165334665200000001\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::120569644156:user/charlie\n  username: charlie\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-12-05T19:02:05Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"9746","uid":"e9e5b337-be9b-49b5-962d-49b4477ee0e8"}}
  creationTimestamp: "2024-12-05T19:02:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "181551"
  uid: e9e5b337-be9b-49b5-962d-49b4477ee0e8
