apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::120569644156:role/managed-group-eks-node-group-20241205165334665200000001
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::120569644156:user/charlie
      username: charlie
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-05T19:02:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9746"
  uid: e9e5b337-be9b-49b5-962d-49b4477ee0e8
