apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: charliechow27/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb://eksUser:secret123@10.0.2.77:27017/go-mongodb
        - name: SECRET_KEY
          value: secret123